import YAML from "yaml";

import type { StepHarborPolicy } from "../domain/policies.js";
import { getPolicyTemplate } from "./policyTemplates.js";
import type {
  PolicyTemplateName,
  RenderPolicyTemplateOptions
} from "./policyTemplateTypes.js";

const policyToYamlShape = (
  policy: StepHarborPolicy
): Record<string, unknown> => ({
  version: policy.version,
  ...(policy.workspace !== undefined
    ? {
        workspace: {
          ...(policy.workspace.allowedRoots !== undefined
            ? { allowed_roots: policy.workspace.allowedRoots }
            : {}),
          ...(policy.workspace.forbiddenMutationOutsideWorkspace !== undefined
            ? {
                forbidden_mutation_outside_workspace:
                  policy.workspace.forbiddenMutationOutsideWorkspace
              }
            : {})
        }
      }
    : {}),
  ...(policy.protectedBranches !== undefined
    ? { protected_branches: policy.protectedBranches }
    : {}),
  ...(policy.sensitivePaths !== undefined
    ? {
        sensitive_paths: {
          ...(policy.sensitivePaths.critical !== undefined
            ? { critical: policy.sensitivePaths.critical }
            : {}),
          ...(policy.sensitivePaths.high !== undefined
            ? { high: policy.sensitivePaths.high }
            : {}),
          ...(policy.sensitivePaths.medium !== undefined
            ? { medium: policy.sensitivePaths.medium }
            : {})
        }
      }
    : {}),
  ...(policy.validation !== undefined
    ? {
        validation: {
          ...(policy.validation.beforeCommit !== undefined
            ? { before_commit: policy.validation.beforeCommit }
            : {}),
          ...(policy.validation.beforePush !== undefined
            ? { before_push: policy.validation.beforePush }
            : {})
        }
      }
    : {}),
  ...(policy.thresholds !== undefined
    ? {
        thresholds: {
          ...(policy.thresholds.largeDiffFiles !== undefined
            ? { large_diff_files: policy.thresholds.largeDiffFiles }
            : {}),
          ...(policy.thresholds.largeDiffLines !== undefined
            ? { large_diff_lines: policy.thresholds.largeDiffLines }
            : {}),
          ...(policy.thresholds.contextCompletenessMinimum !== undefined
            ? {
                context_completeness_minimum:
                  policy.thresholds.contextCompletenessMinimum
              }
            : {}),
          ...(policy.thresholds.sensitiveContextCompletenessMinimum !==
          undefined
            ? {
                sensitive_context_completeness_minimum:
                  policy.thresholds.sensitiveContextCompletenessMinimum
              }
            : {}),
          ...(policy.thresholds.maxRetriesSameGoal !== undefined
            ? { max_retries_same_goal: policy.thresholds.maxRetriesSameGoal }
            : {}),
          ...(policy.thresholds.maxSessionMinutesWithoutProgress !== undefined
            ? {
                max_session_minutes_without_progress:
                  policy.thresholds.maxSessionMinutesWithoutProgress
              }
            : {})
        }
      }
    : {}),
  ...(policy.rules !== undefined ? { rules: policy.rules } : {})
});

export const renderPolicyTemplate = (
  name: PolicyTemplateName | string,
  options: RenderPolicyTemplateOptions = {}
): string | null => {
  const template = getPolicyTemplate(name);

  if (template === undefined) {
    return null;
  }

  const body = YAML.stringify(policyToYamlShape(template.policy), {
    lineWidth: 0
  });
  const includeHeader = options.includeHeader ?? true;

  if (!includeHeader) {
    return body;
  }

  return [
    "# StepHarbor policy",
    "# Generated by stepharbor init",
    `# Template: ${template.name}`,
    "# Review before using in production.",
    "",
    body
  ].join("\n");
};
